@startuml entity-relation

enum TaskStatus {
  queued
  done
  failed
  running
  canceled
}

enum Source {
  github
  huggingface
  local
}

entity AIModel {
  * ID : CHAR(32)
  * Version : INTEGER
  * Name : VARCHAR
  * ModelTag : VARCHAR
  * Source : VARCHAR(11)
  TrainedFromID : CHAR(32)
  CreatedAt : DATETIME
  UpdatedAt : DATETIME
}

entity UploadDatasetTask {
  * ID : CHAR(32)
  tag : VARCHAR(128)
  TaskStatus : VARCHAR(7)
  EndDate : DATETIME
  ErrorMsg : VARCHAR
  CreatedAt : DATETIME
  UpdatedAt : DATETIME
}

entity SynthesisTask {
  * ID : CHAR(32)
  TaskStatus : VARCHAR(7)
  EndDate : DATETIME
  ErrorMsg : VARCHAR
  CreatedAt : DATETIME
  UpdatedAt : DATETIME
}

entity UploadTask {
  * ID : CHAR(32)
  Tag : VARCHAR(128)
  TaskStatus : VARCHAR(7)
  Source : VARCHAR(11)
  EndDate : DATETIME
  ErrorMsg : VARCHAR
  CreatedAt : DATETIME
  UpdatedAt : DATETIME
}

entity Dataset {
  * ID : CHAR(32)
  Version : INTEGER
  FileName : VARCHAR(255)
  Name : VARCHAR(128)
  Classification : VARCHAR(16)
  Rows : INTEGER
  Source : VARCHAR(11)
  CreatedAt : DATETIME
  UpdatedAt : DATETIME
  SynthesisID : CHAR(32)
}

entity TrainingTask {
  * ID : CHAR(32)
  TaskStatus : VARCHAR(7)
  EndDate : DATETIME
  ErrorMsg : VARCHAR
  TrainedModelID : CHAR(32)
  CreatedAt : DATETIME
  UpdatedAt : DATETIME
  ValidationDatasetPath : VARCHAR
  TrainRuntime : FLOAT
  TrainSamplesPerSecond : FLOAT
  TrainStepsPerSecond : FLOAT
  TrainLoss : FLOAT
  Epoch : FLOAT
}

entity EvaluationTask {
  * ID : CHAR(32)
  TaskStatus : VARCHAR(7)
  EndDate : DATETIME
  ErrorMsg : VARCHAR
  ModelID : CHAR(32)
  ModelTag : VARCHAR
  DatasetInfo : VARCHAR
  BaselineModelTag : VARCHAR
  CreatedAt : DATETIME
  UpdatedAt : DATETIME
  Progress : FLOAT
  EvaluationMetrics : VARCHAR
  BaselineMetrics : VARCHAR
  EvaluationSummary : VARCHAR
}

entity InferenceCounter {
  * ID : CHAR(32)
  AIModelID : CHAR(32)
  CreatedAt : DATETIME
}

AIModel::TrainedFromID }o--|| AIModel::id : TrainedFrom
Dataset::SynthesisID }o--|| SynthesisTask::id : Synthesis
TrainingTask::TrainedModelID }o--|| AIModel::id : TrainedModel
EvaluationTask::ModelID }o--|| AIModel::id : Model
InferenceCounter::AIModelID }o--|| AIModel::id : AIModel

@enduml