@startuml use-cases-uploads
left to right direction
skinparam actorStyle awesome

actor User

package "Model Upload Service" {
    usecase Github as "Upload GitHub Model"
    usecase HF as "Upload HuggingFace Model"
    usecase Zip as "Upload ZIP Archive"

    usecase CreateTask as "Create Upload Task"
    usecase BGProcess as "Background Process Upload"
    usecase SaveDB as "Save Model to DB"
    usecase ValidateFiles as "Validate Model Files"
    usecase CacheModel as "Cache Model Locally"
}

User --> Github : Request upload\n(owner, repo, branch)
User --> HF : Request upload\n(modeltag, revision)
User --> Zip : Upload ZIP file\n(optional base name)

Github --> CreateTask
HF --> CreateTask
Zip --> CreateTask

CreateTask --> BGProcess

BGProcess --> ValidateFiles
BGProcess --> CacheModel
BGProcess --> SaveDB

ValidateFiles --> BGProcess : sucess or fail
CacheModel --> BGProcess : sucess or fail
SaveDB --> BGProcess : sucess or fail

@enduml
