site_name: Vectorize - Text Embedding Service
site_description: AWP Text Embedding Service for Robert Bosch GmbH
repo_url: https://github.com/Yukasama/vectorize
repo_name: vectorize

dev_addr: "localhost:8001"

theme:
  name: material
  favicon: logo/favicon.ico
  logo: logo/android-chrome-192x192.png
  palette:
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: deep purple
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - toc.follow
  language: en

markdown_extensions:
  - toc:
      permalink: true

watch: [docs, mkdocs.yaml, src/vectorize]

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          src: src/vectorize
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            merge_init_into_class: true

  - build_plantuml:
      render: "server"
      server: "http://www.plantuml.com/plantuml"
      disable_ssl_certificate_validation: true
      output_format: "svg"
      diagram_root: "docs/diagrams"
      output_folder: "out"
      input_folder: "src"
      input_extensions: "plantuml"

nav:
  - Vectorize: index.md
  - Getting Started:
      - Installation: installation.md
      - Contributing: contributing.md
      - Configuration: configuration.md
      - Monitoring with Grafana: grafana.md
      - Run local CI with Act: act.md
      - Technicals:
          - Database: database.md
          - Logging: logging.md
  - User Guides:
      - AI Models: guides/models.md
      - Datasets: guides/datasets.md
      - Evaluation: guides/evaluation.md
      - Inference: guides/inference.md
      - Synthetic Generation: guides/synthesis.md
      - Tasks: guides/tasks.md
      - Training: guides/training.md
      - Upload: guides/upload.md
  - API Reference:
      - Overview: api.md
      - Endpoints:
          - Common/Health: api/common.md
          - AI Models: api/models.md
          - Datasets: api/datasets.md
          - Evaluation: api/evaluation.md
          - Inference: api/inference.md
          - Synthetic Generation: api/synthesis.md
          - Tasks: api/tasks.md
          - Training: api/training.md
          - Upload: api/upload.md
  - Architecture:
      - API Endpoints: diagrams/api-endpoints.md
      - Entity Relationship: diagrams/entity-relation.md
  - Use Cases:
      - AI Models: diagrams/use-cases-models.md
      - Datasets: diagrams/use-cases-datasets.md
      - Evaluation: diagrams/use-cases-evaluation.md
      - Inference: diagrams/use-cases-inference.md
      - Synthetic Generation: diagrams/use-cases-synthesis.md
      - Tasks: diagrams/use-cases-tasks.md
      - Training: diagrams/use-cases-training.md
      - Upload: diagrams/use-cases-upload.md
  - About:
      - Contributors: contributors.md
