services:
  redis:
    image: redis:7-alpine
    container_name: vectorize_redis
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks: [vectorize-network]
    restart: unless-stopped
    cap_drop: [ALL]
    cap_add: [CHOWN, SETGID, SETUID]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  dramatiq_worker:
    build: ../..
    container_name: vectorize_dramatiq_worker
    command: ["dramatiq", "vectorize.tasks", "-p", "4", "-t", "4", "--verbose"]
    networks: [vectorize-network]
    environment:
      ENV: production
      DATABASE_URL: sqlite+aiosqlite:///db/app.db
      REDIS_URL: redis://redis:6379
      UPLOAD_DIR: /app/data/datasets
      MODELS_DIR: /app/data/models
      DB_DIR: /app/db
      TZ: Europe/Berlin
      LOG_LEVEL: INFO
      HF_HOME: /app/data/hf_home
    volumes:
      - datasets_data:/app/data/datasets
      - models_data:/app/data/models
      - db_data:/app/db
      - hf_home_data:/app/data/hf_home
    cap_drop: [ALL]
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[d]ramatiq' || exit 1"]
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 60s
