services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports: [9000:9000, 9092:9092]
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs:ro
      - sonarqube_extensions:/opt/sonarqube/lib/extensions
    environment:
      TZ: Europe/Berlin
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4096M
        reservations:
          cpus: "2.0"
          memory: 2048M

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
