services:
  vectorize:
    build: ../..
    container_name: vectorize
    volumes:
      - datasets_data:/app/data/datasets
      - models_data:/app/data/models
      - db_data:/app/db
    environment:
      ENV: production
      DATABASE_URL: sqlite+aiosqlite:///./db/app.db
      UPLOAD_DIR: /app/data/datasets
      MODELS_DIR: /app/data/models
      DB_DIR: /app/db
      LOG_LEVEL: INFO
    networks: [vectorize-network]
    restart: unless-stopped
    cap_drop: [ALL]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  datasets_data:
  models_data:
  db_data:
